### ISSUE TITLE
Initial Tasks to Make This Operator more Generic

### ISSUE THREAD

**Issue by jcantrill** [openshift/elasticsearch-operator#102]
Following are an initial set of tasks to make this operator more generic for consumption outside the context of OK cluster logging.  This list is by no means exhaustive and additions are welcome.

- [ ] Extract Initialization Logic to separate task
- [ ] Affinity/Anti-affinity rules. Need to change/customizable???
- [ ] Proxy container customization???
- [ ] Remove/Modify Readiness probe
- [ ] Custom Certificate entries on start?
- [ ] Multiple ES configs by role?
- [ ] Custom ENV definition??
- [ ] Remove dependency on `es_util`
- [ ] Openshift specific RBAC??
- [ ] Optional deploy of ServiceMonitor?

**Comment by ewolinetz** [comment]
https://jira.coreos.com/browse/LOG-326
