### ISSUE TITLE
Configure logger

### ISSUE THREAD

**Issue by josefkarasek** [openshift/elasticsearch-operator#12]
What about logging in JSON instead of pattern?
Now we log eg:
```
INFO[1104] cluster elastic1 required action is: ClusterOK 
```
Configuring `logrus` is easy, see: https://github.com/josefkarasek/formatted-logs/blob/master/main.go#L17

**Comment by ewolinetz** [comment]
Do you have an example output in the JSON format?

**Comment by richm** [comment]
I think it is more important to be consistent with what ever other component of openshift is using - we don't want to move to json file log format while every other component is using something else

That being said - we should allow users/admins to globally change the way all openshift components are logged e.g. if there is some sort of log4go configuration file that applies to all components running on a node, or all components in the cluster.

**Comment by ewolinetz** [comment]
I think we also need to go through and clean up the output for the operator(s). Looking at the other demos, they only seem to write output when a change is happening. We should not see the same message repeat multiple times in a row.

**Comment by josefkarasek** [comment]
Log format configurable either by `--log-format=logfmt|json` or `LOG_FORMAT` envar. `logfmt` (plaintext) is the default.

Log level configurable either by `--log-level=debug|info|warning|warn|error|fatal|panic`[1] or `LOG_LEVEL` envar. `info` is the default.

Cmd arguments take preference.

[1] https://github.com/sirupsen/logrus/blob/master/logrus.go#L25

**Comment by richm** [comment]
How would we dynamically set this? Do we need to add log level to the elasticsearch CR?  and add code for it in the operator?  We can't `oc set env deploy/elasticsearch-operator LOG_LEVEL=debug` because OLM will reset it.  Do we need a configmap for this?

**Comment by josefkarasek** [comment]
The operator is a stateless application. I don't see any issue with restarting it. It runs in 5 seconds intervals anyways.

**Comment by jcantrill** [comment]
Re purposing this issue to move all logging to rely on the logging adapter functions that wrap logrus.  The operator currently has 2 log libraries it uses and these should collapse into one where we can configure it as we like.
