### ISSUE TITLE
Is there is a way to specify "ImagePullPolicy"?

### ISSUE THREAD

**Issue by jkandasa** [openshift/elasticsearch-operator#180]
Is there is a way to specify "ImagePullPolicy" for elasticsearch image and proxy image on the operator cr file?

Problem: if we use `quay.io/openshift/origin-logging-elasticsearch5:latest`, it is not pulling a new image if there is update found. since by default, it is marked as `imagePullPolicy: IfNotPresent`

**Comment by richm** [comment]
https://github.com/openshift/elasticsearch-operator/pull/177

**Comment by jcantrill** [comment]
The dev deployment was modified to make the policy Always.
