### ISSUE TITLE
Operator installation fails on OCP 4.4 cluster

### ISSUE THREAD

**Issue by kevinearls** [openshift/elasticsearch-operator#319]
I tried to install the ElasticSearch operator from the Red Hat operator source using OperatorHub on an OCP 4.4 cluster (from build 4.4.0-0.nightly-2020-04-16-231032)  OperatorHub shows ES operator version 4.4.0-202004130743 using image registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:efa7b8b8225148d459e07071123ffb3d86a053fade04128fdf239a69e2188213

I installed using update channel 4.4,  all namespaces for installation mode, and automatic approval strategy.  The operator fails to install with:

Failed to pull image "registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:efa7b8b8225148d459e07071123ffb3d86a053fade04128fdf239a69e2188213": rpc error: code = Unknown desc = Error reading manifest sha256:efa7b8b8225148d459e07071123ffb3d86a053fade04128fdf239a69e2188213 in registry.redhat.io/openshift4/ose-elasticsearch-operator: error parsing HTTP 404 response body: invalid character 'F' looking for beginning of value: "File not found.\""

@objectiser @mattmahoneyrh

**Comment by jcantrill** [comment]
Please open a bugzilla for this issue as this is something that would require resolution from our RCM process: https://bugzilla.redhat.com/
