### ISSUE TITLE
connect to elastic from service

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/elasticsearch-operator#325]
If I use the [elastic and cluster logging operators in openshift](https://docs.openshift.com/container-platform/4.1/logging/efk-logging-deploying.html) then presumably the auth used on kibana is the same as the openshift cluster itself, so it requires a bearer token to access. Is this also the case for the elastic? I'm wondering whether there's any easy way to connect to it from a backend service.

**Comment by jcantrill** [comment]
What role does the person have that you wish to connect to the service? 

If you have admin rights to the openshift-logging namespace you can do something like:

  `oc exec -c elasticsearch $pod -- es_util --query=<es api query>` and it will utilize the admin certs.

If you wish to grant  access to a wider audience you can expose the service as a route and curl it using the route and elastic api.  Additionally you would need to add your token into the request header `-XAuthorization: Bearer $(oc whoami -t)` which should allow you through if you have the proper permissions

**Comment by ryandawsonuk** [comment]
Is there a way of getting a long-lived token that I could plug into an app running in the cluster so the app could make calls to elastic?

**Comment by jcantrill** [comment]
> Is there a way of getting a long-lived token that I could plug into an app running in the cluster so the app could make calls to elastic?

Isn't that a serviceaccount token?

**Comment by ryandawsonuk** [comment]
I'll try that out.

**Comment by ryandawsonuk** [comment]
Am able to connect using curl. Was hoping to [use python client](https://github.com/elastic/elasticsearch-py/issues/1221) but that is a separate issue so I'll close this one.
