### ISSUE TITLE
permission required to write to index

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/elasticsearch-operator#338]
I'm writing to [elastic using a serviceaccount](https://github.com/openshift/elasticsearch-operator/issues/325). Naturally I need to grant permissions to that service account or else I get:
```
'no permissions for [indices:data/write/update] and User [name=system:serviceaccount:logs:elasticseldon, roles=[gen_project_operations, gen_user_29547d51e00776c5acf0bed34e1ba5bb9736a4ef, gen_kibana_29547d51e00776c5acf0bed34e1ba5bb9736a4ef]]'
```
I can write if I grant the serviceaccount cluster-admin with `oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:logs:elasticseldon`. 

Am looking for a narrower role that I can allocate instead. I've tried variations on `oc adm policy add-role-to-user -n logs indices:write system:serviceaccount:logs:elasticseldon` but not found one that enables me to write. Any ideas on this? Apologies if the answer is obvious to someone who knows this permissions model better than I do.

**Comment by jcantrill** [comment]
Permissions are only loosely based on openshift and in 4.4 and early  [1] are defined by [1]. The remaining roles and permissions are essentially static and would require you to update these directly. Note, however, these are re-initialized on pod restart.

[1] https://github.com/openshift/origin-aggregated-logging/blob/master/docs/access-control.md
[2] https://github.com/openshift/origin-aggregated-logging/blob/release-4.4/elasticsearch/sgconfig/sg_roles_mapping.yml

**Comment by ryandawsonuk** [comment]
Ok, thanks. I guess a serviceaccount won't ever do a login from a UI so it won't follow that path to generation. Presumably the only static roles available to it then are roles like [cluster-admin and cluster-reader](https://github.com/openshift/origin-aggregated-logging/search?q=%22oc+adm+policy%22&unscoped_q=%22oc+adm+policy%22).

**Comment by ryandawsonuk** [comment]
Am now trying with openshift 4.6 and discovering that `oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:logs:elasticseldon` does not give the service account write permissions anymore. I guess something has changed since 4.4. @jcantrill Is there an easy way to grant write permission to a service account for 4.6?

**Comment by jcantrill** [comment]
The collector deployed by the CLO is intentionally the only one generally allowed to write to the cluster.  This is to limit the exposure of who can create indices and possible destabilize the cluster.   EO is designed around the cluster logging use-case with the intention to make it more generic but it is not there yet, if ever.  You would need to alter permissions contained in the image as advised https://github.com/openshift/elasticsearch-operator/issues/338#issuecomment-622373566 but note the draw backs

**Comment by ryandawsonuk** [comment]
Ok, will use the ECK operator instead. Thanks.

**Comment by sanapals** [comment]
Hi @ryandawsonuk ,
Can you please let me know if you are able to get around with this issue?  I am in same situation, where I need a service account to be able to manage Elasticsearch indices. We are running on OCP4.7. I am not able to find a way to achieve this.
