### ISSUE TITLE
search queries timing out - possible setup issue

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/elasticsearch-operator#339]
I'm port-forwarding to the elastic and am able to perform get requests to particular docs and posts to create docs. But when search using `_search` my queries all time out. I'm running queries that I know match to the docs that I inserted. I've also tried [basic example queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-query-ex-request) like
```
{
    "query": {
        "query_string" : {
            "query" : "(new york city) OR (big apple)",
            "default_field" : "content"
        }
    }
}
```
I can't find any errors in the logs and I've not got a timeout in postman so it must be timing out server-side. I've tried to get to the kibana UI but I get an auth error when I port-forward to it and I don't have any Logging option under Monitoring in the openshift console. 

Perhaps I don't have the kibana option because I installed to a custom namespace called 'logs' rather than 'openshift-logging' [as the guide suggests](https://docs.openshift.com/container-platform/4.1/logging/efk-logging-deploying.html).

I did reduce the memory allocation so I'll try again with more resource. But I don't see anything in the logs when I run queries. 

Is https://docs.openshift.com/container-platform/4.1/logging/efk-logging-deploying.html the intended way to setup the operator? I suspect I'm deviating from intentions by putting things in different namespaces and playing with resources but just want to double-check this.

**Comment by jcantrill** [comment]
"openshift-logging" is a hard dependency for clusterlogging.

**Comment by ryandawsonuk** [comment]
Have noticed that when I try to change the resources in an existing ClusterLogging instance it fails to apply the change and gives error
```
{"level":"error","ts":1588583429.7738824,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"proxyconfig-controller","request":"/cluster","error":"Unable to create or update collection for \"\": Failure deleting logcollector service account: an empty namespace may not be set when a resource name is provided","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/openshift/cluster-logging-operator/_output/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
Presumably I need to [run it using the instructions and namespaces from the docs](https://docs.openshift.com/container-platform/4.1/logging/efk-logging-deploying.html).

**Comment by ryandawsonuk** [comment]
Using those install instructions the queries do not time out.
