### ISSUE TITLE
Kibana server is not ready after updating Logging and ES operators to 4.5

### ISSUE THREAD

**Issue by alexeykazakov** [openshift/elasticsearch-operator#457]
After upgrading an OCP 4.4.16 to 4.5.5 and switching (and updating) Elasticsearch and Logging operators to 4.5 channels I see the following when try to open Kibana from the web console:

![kibana2](https://user-images.githubusercontent.com/620087/90187087-15329900-dd6e-11ea-9c50-c3135129141f.png)

This is what is in the logs:

```
  log   [21:01:02.725] [info][migrations] Creating index .kibana_7.
  log   [21:01:02.743] [warning][migrations] Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_7 and restarting Kibana.
```

**Comment by ewolinetz** [comment]
to get to the logs i needed to `rsh` into the pod, adjust the config to be a port other than `5601` and comment out the line that set to only show errors in the logs. then i started up another instance of kibana

**Comment by ewolinetz** [comment]
closing to track here: https://bugzilla.redhat.com/show_bug.cgi?id=1870371
