### ISSUE TITLE
Deployments are not removed when the CR's are removed

### ISSUE THREAD

**Issue by jcantrill** [openshift/elasticsearch-operator#51]
Playing around with cluster logging it doesnt appear the Deployments get removed when the CR gets removed.  Need to confirm

**Comment by josefkarasek** [comment]
AFAIK cascade deletes have to be issued explicitly.
The operator sets owner references on its managed objects, so the following command should delete all es objects in *foreground* fashion.
```
oc delete elasticsearch my-es --cascade=true
```

Also, did you try to wait a bit after deleting the CR?
K8s' garbage collector might kick in after some time and recycle orphaned objects. But I'm not sure about this.

@ewolinetz what do you think?

**Comment by ewolinetz** [comment]
I don't believe we need to use `--cascade=true`, I've just deleted the parent object which is the ClusterLogging CR object.

@jcantrill K8s does the clean up, I would verify that you have an `OwnerRef` in each of the deployments. It should point to the Elasticsearch CR object for that specific cluster (the OwnerRef of that Elasticsearch object would be the ClusterLogging CR so long as the CLO created it)

**Comment by jcantrill** [comment]
Closing as I don't see this happening any longer
