### ISSUE TITLE
Unable to create new elasticsearch using default settings

### ISSUE THREAD

**Issue by rmorrise** [openshift/elasticsearch-operator#519]
When I try to create a new elasticsearch using the default settings on the OpenShift form from the catalog, the operation fails. The following messages are displayed:
```
Elasticsearch Client Status
  The field status.pods.client is invalid
Elasticsearch Data Status
  The field status.pods.data is invalid
Elasticsearch Master Status
  The field status.pods.master is invalid
...
Invalid SettingsWrong RedundancyPolicy selected. Choose different RedundancyPolicy or add more nodes with data roles
```

Here is the operator version installed:
```
Elasticsearch Operator
4.3.37-202009151447.p0 provided by Red Hat, Inc
```

**Comment by rmorrise** [comment]
Update: I tried to edit the YAML and change the RedundancyPolicy to ZeroRedundancy, but this did not resolve the issue.

**Comment by jcantrill** [comment]
@rmorrise please explicitly detail the steps you used for creating a cluster using the EO
