### ISSUE TITLE
Not launching kibana instance from elasticsearch operator

### ISSUE THREAD

**Issue by sreenichelikam** [openshift/elasticsearch-operator#556]
**Describe the bug**
 Not launching kibana instance from elasticsearch operator when created instance for kibana. Not observed any errors or activity related to this. 

**Environment**
-  Openshift 4.5
-  Red Hat OpenShift Jaeger 1.17.6 provided by Red Hat. Created Jeager Production strategy instance with elasticsearch storage.
- Elasticsearch Operator 4.5.0-202010161522.p0 provided by Red Hat, Inc

**Logs**
Not observed any errors or activity related to this. 

**Expected behavior**
Should be able to create kibana instance and integrate with elasticsearch

**Actual behavior**
Not launching kibana instance from elasticsearch operator

**To Reproduce**
1.  Deploy jeager production strategy instance in openshift 4.5 cluster.
2.  Try to create kibana instance

**Additional context**

**Comment by ewolinetz** [comment]
The Jaeger operator does not create a kibana CR which the Elasticsearch Operator looks for when creating a kibana instance. If you would like Jaeger to provide a means to do this, please open an issue on their repo as the kibana instance will also need to have certs created for it to talk to ES.
