### ISSUE TITLE
Kibana POD is not getting created in OCP 4.6 cluster (Elasticsearch instance + POD got created, Kibana instance created but POD is not created)

### ISSUE THREAD

**Issue by SAbdulRahuman** [openshift/elasticsearch-operator#571]
**Describe the bug**
In Openshift 4.6 cluster and created a project called "ext-elasticsearch". Using operatorhub (OCP web Console --> operators --> operatorHub) installed "**Elasticsearch Operator 4.6.0-202010311441.p0 provided by Red Hat, Inc**".

![image](https://user-images.githubusercontent.com/7375503/98854154-35164d80-2480-11eb-9900-5376efe1d334.png)

After installing **Elasticsearch Operator 4.6.0**, i created instances of Elasticsearch and Kibana.

1) Created ElasticSearch Instance (OCP web Console --> Installed Operator --> Project: ext-elasticsearch)

![image](https://user-images.githubusercontent.com/7375503/98854714-ed43f600-2480-11eb-8071-7690bc0729b4.png)

![image](https://user-images.githubusercontent.com/7375503/98854877-2aa88380-2481-11eb-8524-e6ac6c5b138c.png)

And able to verify that **Elasticsearch** instance is created and **elasticsearch** POD  is **Running**

2) **Issue** Created Kibana Instance (OCP web Console --> Installed Operator --> Project: ext-elasticsearch)

![image](https://user-images.githubusercontent.com/7375503/98855092-7bb87780-2481-11eb-9254-6e2d57fcb43a.png)

![image](https://user-images.githubusercontent.com/7375503/98855194-9db1fa00-2481-11eb-89fd-0851bebda6ae.png)

Kibana instance is created but POD is not created

![image](https://user-images.githubusercontent.com/7375503/98855332-d7830080-2481-11eb-9042-efe42e8c616c.png)

![image](https://user-images.githubusercontent.com/7375503/98855412-f41f3880-2481-11eb-8382-43e2c25735c4.png)

**Environment**
- Openshift version is **4.6.1**
- Elasticsearch operato version is **Elasticsearch Operator 4.6.0-202010311441.p0 provided by Red Hat, Inc**

**Logs of `oc get all`**
```
$ oc get all

NAME                                                READY   STATUS    RESTARTS   AGE
pod/elasticsearch-cdm-plj1ai36-1-5dd4557c6c-744zq   2/2     Running   0          8m13s

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
service/elasticsearch           ClusterIP   172.25.203.46    <none>        9200/TCP    8m18s
service/elasticsearch-cluster   ClusterIP   172.25.39.99     <none>        9300/TCP    8m19s
service/elasticsearch-metrics   ClusterIP   172.25.110.229   <none>        60001/TCP   8m18s
service/kibana                  ClusterIP   172.25.31.191    <none>        443/TCP     4m48s

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/elasticsearch-cdm-plj1ai36-1   1/1     1            1           8m16s

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/elasticsearch-cdm-plj1ai36-1-5dd4557c6c   1         1         1       8m16s

NAME                              HOST/PORT                                   PATH   SERVICES   PORT    TERMINATION          WILDCARD
route.route.openshift.io/kibana   kibana-ext-elasticsearch.apps-crc.testing          kibana     <all>   reencrypt/Redirect   None

```
**Expected behavior**
Kibana POD should be running in namespace "ext-elasticsearch"

**Actual behavior**
Kibana POD is not running in namespace "ext-elasticsearch"

**To Reproduce**
1. Install "**Elasticsearch Operator 4.6.0-202010311441.p0 provided by Red Hat, Inc**" (selecting all namespace option)
2. Create a project called "ext-elasticsearch"
3. Create instance of elasticsearch using web console
    i. OCP web console --> Administrator --> Operators --> Installed Operators --> project: ext-elasticsearch 
    ii. Click **Create Instance** of Elasticsearch and proceed further
4. Create instance of Kibana using web console
    i. OCP web console --> Administrator --> Operators --> Installed Operators --> project: ext-elasticsearch 
    ii. Click **Create Instance** of Kibana and proceed further

**Additional context**
1) Installed elasticsearch operator
![image](https://user-images.githubusercontent.com/7375503/98856586-c6d38a00-2483-11eb-8c1b-552dd8676c5d.png)

2) Created Instance of ElasticSearch + Kibana 
![image](https://user-images.githubusercontent.com/7375503/98856667-e7034900-2483-11eb-904a-eb1e2681877e.png)

3) But Kibana POD is not created 
![image](https://user-images.githubusercontent.com/7375503/98856715-fe423680-2483-11eb-8675-b7d7802c625c.png)

**Comment by ewolinetz** [comment]
@SAbdulRahuman typically the elasticsearch and kibana CRs are created and managed by the Cluster Logging Operator because it also creates the required secrets for these components to communicate.

Are there any logs in the Elasticsearch Operator pod that indicate why you are not seeing the pods (or deployment) created?

**Comment by SAbdulRahuman** [comment]
@ewolinetz 
I don't see any POD with name "elasticsearch operator". All i see the below pods

```
$ oc get all
NAME                                                READY   STATUS    RESTARTS   AGE
pod/elasticsearch-cdm-zdhmc0mt-1-69479588fc-mgn2c   1/2     Running   0          15m

NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/elasticsearch           ClusterIP   172.25.98.102   <none>        9200/TCP    15m
service/elasticsearch-cluster   ClusterIP   172.25.36.128   <none>        9300/TCP    15m
service/elasticsearch-metrics   ClusterIP   172.25.141.8    <none>        60001/TCP   15m
service/kibana                  ClusterIP   172.25.200.12   <none>        443/TCP     4m47s

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/elasticsearch-cdm-zdhmc0mt-1   0/1     1            0           15m

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/elasticsearch-cdm-zdhmc0mt-1-69479588fc   1         1         0       15m

NAME                              HOST/PORT                                   PATH   SERVICES   PORT    TERMINATION          WILDCARD
route.route.openshift.io/kibana   kibana-ext-elasticsearch.apps-crc.testing          kibana     <all>   reencrypt/Redirect   None
s
```

**Comment by huikang** [comment]
Have  you tried `make deploy-example-secret` to generate the secret?

**Comment by SAbdulRahuman** [comment]
No, i did not tried ```make deploy-example-secret``` to generate secret instead created secret "elasticsearch" and added secret to the namespace "ext-elasticsearch"

**Comment by SAbdulRahuman** [comment]
I have tried to create "elasticsearch" in namespace "ext-elasticsearch" using below steps, It seems Elasticsearch and Kibana are running.  In Short, i used "Cluster logging" operator as well but my requireent is i need to create ElasticSearch + Kibana in any namespace without ClusterLogging operator.


Steps:
1) created a project "ext-elastic-search"
2) Installed Red Hat provided "ElasticSearch" operator
3) Installed Red Hat provided "Cluster Logging" operator
4) Create CR instance using below YAML
```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: ext-elasticsearch
spec:
  logStore:
    elasticsearch:
      nodeCount: 1
      redundancyPolicy: ZeroRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: 100m
          memory: 1Gi
    retentionPolicy:
      application:
        maxAge: 7d
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      replicas: 1
    type: kibana
```

5) able to see Elasticsearch + Kibana UI running and also Kibana UI is accessible using route URL

```
$ oc get all -n ext-elasticsearch
NAME                                                READY   STATUS      RESTARTS   AGE
pod/cluster-logging-operator-5ddcfffc9b-w55x6       1/1     Running     0          138m
pod/elasticsearch-cdm-reyqcf71-1-67d47fcddd-s5msg   2/2     Running     0          72m
pod/elasticsearch-delete-app-1606194900-bkdl4       0/1     Completed   0          6m22s
pod/elasticsearch-delete-audit-1606194900-vsp59     0/1     Completed   0          6m12s
pod/elasticsearch-delete-infra-1606194900-229tz     0/1     Completed   0          5m52s
pod/elasticsearch-rollover-app-1606194900-fj2mr     0/1     Completed   0          5m12s
pod/elasticsearch-rollover-audit-1606194900-8xq4g   0/1     Completed   0          3m52s
pod/elasticsearch-rollover-infra-1606194900-hzpl8   0/1     Completed   0          72s
pod/kibana-7b59c94f5f-vq4nc                         2/2     Running     0          74m

NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/cluster-logging-operator-metrics   ClusterIP   172.30.164.224   <none>        8383/TCP,8686/TCP   138m
service/elasticsearch                      ClusterIP   172.30.174.75    <none>        9200/TCP            74m
service/elasticsearch-cluster              ClusterIP   172.30.46.67     <none>        9300/TCP            74m
service/elasticsearch-metrics              ClusterIP   172.30.95.233    <none>        60001/TCP           74m
service/kibana                             ClusterIP   172.30.186.83    <none>        443/TCP             74m

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cluster-logging-operator       1/1     1            1           138m
deployment.apps/elasticsearch-cdm-reyqcf71-1   1/1     1            1           72m
deployment.apps/kibana                         1/1     1            1           74m

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/cluster-logging-operator-5ddcfffc9b       1         1         1       138m
replicaset.apps/elasticsearch-cdm-reyqcf71-1-67d47fcddd   1         1         1       72m
replicaset.apps/kibana-7b59c94f5f                         1         1         1       74m

NAME                                                COMPLETIONS   DURATION   AGE
job.batch/elasticsearch-delete-app-1606194900       1/1           4s         6m24s
job.batch/elasticsearch-delete-audit-1606194900     1/1           3s         6m23s
job.batch/elasticsearch-delete-infra-1606194900     1/1           3s         6m23s
job.batch/elasticsearch-rollover-app-1606194900     1/1           3s         6m23s
job.batch/elasticsearch-rollover-audit-1606194900   1/1           2s         6m23s
job.batch/elasticsearch-rollover-infra-1606194900   1/1           3s         6m23s

NAME                                         SCHEDULE       SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/elasticsearch-delete-app       */15 * * * *   False     0        6m32s           71m
cronjob.batch/elasticsearch-delete-audit     */15 * * * *   False     0        6m32s           71m
cronjob.batch/elasticsearch-delete-infra     */15 * * * *   False     0        6m32s           71m
cronjob.batch/elasticsearch-rollover-app     */15 * * * *   False     0        6m32s           71m
cronjob.batch/elasticsearch-rollover-audit   */15 * * * *   False     0        6m32s           71m
cronjob.batch/elasticsearch-rollover-infra   */15 * * * *   False     0        6m32s           71m

NAME                                     HOST/PORT                                                       PATH   SERVICES        PORT            TERMINATION          WILDCARD
route.route.openshift.io/elasticsearch   elasticsearch-ext-elasticsearch.apps.ocp4akash01.c4lab5.local          elasticsearch   elasticsearch                        None
route.route.openshift.io/kibana          kibana-ext-elasticsearch.apps.ocp4akash01.c4lab5.local                 kibana          <all>           reencrypt/Redirect   None
```

Now Can you please share steps and guide me how to install Elasticsearch operator and bring Elasticsearch + Kibana as RUNNING state ?.

**Comment by ewolinetz** [comment]
@SAbdulRahuman as Hui had eluded above, to create an elasticsearch cluster after the elasticsearch operator has been installed in the `openshift-operators-redhat` namespace you will need to create the elasticsearch CR (and kibana) and provide the required secrets in the namespace that you created your CRs in.

CLO will create the CRs and secrets for you already. I would advise looking into how that is done in the cluster-logging-operator repo if you want to use EO in a production capacity without CLO.
