### ISSUE TITLE
Dangerous to allow individual nodes to overwrite the general characteristics of all nodes

### ISSUE THREAD

**Issue by jcantrill** [openshift/elasticsearch-operator#59]
The Elasticsearch CR allows specification of attributes to be applied to all nodes that can be over-ridden by specifications of individual nodes.  The simple implementation is to reuse the stuct.  In theory, you can override the image of a specific node which seems like a really BAD idea.  We should re-evaluate `ElasticsearchNodeSpec` [1] to determine the attributes for which it does not make sense to override on individual nodes.
 
[1] https://github.com/openshift/elasticsearch-operator/blob/master/pkg/apis/elasticsearch/v1alpha1/types.go#L107

**Comment by jcantrill** [comment]
@ewolinetz My concerns here may be addressed by your refactorings

**Comment by ewolinetz** [comment]
It looks like resources can be overridden still... is that a concern or was it just images?

**Comment by jcantrill** [comment]
> It looks like resources can be overridden still... is that a concern or was it just images?

It reasonable to me to override resources per individual node types.  It is NOT to be able to override images.  Allowing override of the image makes it dangerously possible to mix versions that may not be compatible.

**Comment by jcantrill** [comment]
@ewolinetz did we address this?  can we close

**Comment by ewolinetz** [comment]
https://github.com/openshift/elasticsearch-operator/blob/master/pkg/apis/logging/v1/elasticsearch_types.go#L82-L89
