### ISSUE TITLE
Enable travis tests for openshift

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/elasticsearch-operator#6]
As of now the travis tests are running for <https://travis-ci.org/ViaQ/elasticsearch-operator> but we would like to make it run for <https://travis-ci.org/openshift/elasticsearch-operator> as well (or primarily, right?).

Among others the build status in README.md is referencing to <https://travis-ci.org/ViaQ/elasticsearch-operator> which is confusing.

**Comment by lukas-vlcek** [comment]
@jcantrill @ewolinetz Do you know how we need to talk to? I think this needs to be enabled in GitHub webhooks or something like that...

**Comment by jcantrill** [comment]
@lukas-vlcek Do we need the travis tests?  What specifically do they test?  Are they unit tests to run before something like an Openshift e2e test?
