### ISSUE TITLE
Feature request: Allow setting shard allocation awareness

### ISSUE THREAD

**Issue by dbluxo** [openshift/elasticsearch-operator#620]
When configuring the replication policy, we can [choose](https://docs.openshift.com/container-platform/4.6/logging/config/cluster-logging-log-store.html#cluster-logging-elasticsearch-ha_cluster-logging-store) between different variants:

- ZeroRedundancy
- SingleRedundancy
- MultipleRedundancy
- FullRedundancy

Typically, a production cluster is run across multiple availability zones. If we choose SingleRedundancy or MultipleRedundancy, the [shard allocation awareness](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/allocation-awareness.html#allocation-awareness) that Elasticsearch supports should also be set (optionally) when replicating shards to avoid a replica shard ending up within the same availability zone.

> When running nodes on multiple VMs on the same physical server, on multiple racks, or across multiple zones or domains, it is more likely that two nodes on the same physical server, in the same rack, or in the same zone or domain will crash at the same time, rather than two unrelated nodes crashing simultaneously.

**Comment by ewolinetz** [comment]
We currently do not offer a way to configure node attributes in a managed state with our operator. Wouldn't shard allocation awareness require this first?

**Comment by dbluxo** [comment]
Usually the nodes already have the `topology.kubernetes.io/zone` label.
