### ISSUE TITLE
Elasticsearch-operator scaling info/documentation/manual

### ISSUE THREAD

**Issue by vfabi** [openshift/elasticsearch-operator#629]
Hi All,
Could you please tell me where i can find any documentation,manual,etc on Elasticsearch scaling (-up, -down) for elasticsearch-operator?

**Comment by huikang** [comment]
Hi, @vfabi , you could change the `NodeCount` in your CR yaml file. Scaling up and down is supported by the operator [1].

[1] https://github.com/openshift/elasticsearch-operator/blob/5ac3bc64cfbaa7c64957ee8ab411c0c12b15fc10/test/e2e-olm/elasticsearch_test.go#L145

**Comment by ewolinetz** [comment]
You should also be able to update this by viewing your elasticsearch CR object in the OpenShift Console
