### ISSUE TITLE
Add Curator CronJob in ES operator to manage indices of ES

### ISSUE THREAD

**Issue by bysnupy** [openshift/elasticsearch-operator#86]
When using `ES`(`elasticsearch`) on production env, we consider how to rotate the indices of `ES` for maintenance. I glanced this repo, `Curator` is not included. So I think `ES` operator should include Curator `CronJobs`, it's reasonable.

If you have workaround of this or some plan, such as providing `curator-operator` or manual configuration steps of `curator` job, please close this issue kindly.

Thanks.

**Comment by richm** [comment]
curator is provided by cluster-logging-operator https://github.com/openshift/cluster-logging-operator/blob/master/pkg/k8shandler/curation.go

**Comment by bysnupy** [comment]
Thanks @richm !, I can resolve this issues for your information, I close this issue.
