### ISSUE TITLE
Secret mountpoint needs to be updated

### ISSUE THREAD

**Issue by ewolinetz** [openshift/elasticsearch-operator#9]
The old mountpoint for our secret is `/etc/elasticsearch/secret` per the image change [1] to generate our own jks format keys it needs to be updated to `/etc/openshift/elasticsearch/secret`

[1] https://github.com/openshift/origin-aggregated-logging/commit/0966dbd1d7fa811c2ee66326b09c5c8cee13e8c6

**Comment by josefkarasek** [comment]
PR sent openshift/elasticsearch-operator/pull/13
