### ISSUE TITLE
Broken link to maturity model diagram

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/elasticsearch-operator#95]
There is link to operator maturity model in README.md file in [Why Use An Operator?](https://github.com/openshift/elasticsearch-operator#why-use-an-operator) section.
It is broken, the diagram seem to have moved to <https://github.com/operator-framework/operator-sdk/blob/master/doc/images/operator-maturity-model.png>.

**Comment by jcantrill** [comment]
how about a PR to fix

**Comment by lukas-vlcek** [comment]
You asked for it.
